interface IStaff {
    id: number,
    avatar: string,
    username: string,
    fullName: string,
    password: string,
    dateOfBirth: string,
    gender: string,
    phoneNumber: string,
    email: string,
    status: number,
    address: string,
    roles: string,
    createdAt?: string,
    updatedAt?: string,
}